
   
export const types = {
    SEND_REQUEST_GET_ALL_STATIONS: 'SEND_REQUEST_GET_ALL_STATIONS',
    SEND_REQUEST_GET_ALL_STATIONS_SUCCESS: 'SEND_REQUEST_GET_ALL_STATIONS_SUCCESS',
    SEND_REQUEST_GET_ALL_STATIONS_FAILURE: 'SEND_REQUEST_GET_ALL_STATIONS_FAILURE',
  };